// Generated by unRap v1.06 by Kegetys

class cfgWeapons {
	class Default;	// External class reference
	class ItemCore;	// External class reference
	
	class Loot : Default {
		scope = public;
		value = 0;
		type = VSoft;
		displayName = "Use";
		canDrop = false;
		muzzles[] = {this};
		magazines[] = {"ItemBandage", "ItemHeatPack", "PartWoodPile", "PartFueltank", "PartWheel", "PartGeneric", "PartEngine", "PartVRotor", "PartGlass", "ItemWaterbottle", "ItemWaterbottleUnfilled", "ItemEpinephrine", "ItemMorphine", "ItemBloodbag", "ItemAntibiotic", "ItemPainkiller", "ItemJerrycan", "ItemGenerator", "ItemTent", "ItemSandbag", "ItemTankTrap", "ItemWire", "FoodSteakRaw", "TrashTinCan", "ItemSodaCoke", "ItemSodaPepsi", "ItemSodaMdew", "FoodEdible", "FoodSteakCooked", "FoodCanBakedBeans", "FoodCanSardines", "FoodCanFrankBeans", "FoodCanPasta"};
		modes[] = {this};
		useAction = false;
		useActionTitle = "";
		enableAttack = false;
		showToPlayer = false;
	};

	class ItemMap : ItemCore {
		scope = public;
		displayName = "$STR_ItemMap";
		simulation = "ItemMap";
		model = "\dayz_equip\models\foldedmap.p3d";
		picture = "\ca\ui\data\gear_picture_map_ca.paa";
		descriptionShort = "$STR_ItemMap";
	};

	class ItemWatch : ItemCore {
		scope = public;
		displayName = "$STR_ItemWatch";
		simulation = "ItemWatch";
		//model = "\ca\ui\Watch.p3d";
		picture = "\ca\ui\data\gear_picture_watch_ca.paa";
		descriptionShort = "$STR_ItemWatch";
	};
	
	class ItemCompass : ItemCore {
		scope = public;
		displayName = "$STR_ItemCompass";
		simulation = "ItemCompass";
		//model = "\ca\ui\Compass.p3d";
		picture = "\ca\ui\data\gear_picture_compass_ca.paa";
		descriptionShort = "$STR_ItemCompass";
	};
	
	class ItemGPS : ItemCore {
		scope = public;
		displayName = "$STR_ItemGPS";
		simulation = "ItemGPS";
		//model = "\ca\ui\GPS.p3d";
		picture = "\ca\ui\data\gear_picture_gps_ca.paa";
		descriptionShort = "$STR_ItemGPS";
	};

	class CarHorn; // External class reference
	class BikeHorn : CarHorn {
		drySound[] = {"\ca\weapons\Data\Sound\bicycle_ring_v1", 3.16228, 1, 300};
	};

	class ItemToolbox : ItemCore {
		scope = public;
		displayName = $STR_EQUIP_NAME_2;
		model = "\dayz_equip\models\toolbox.p3d";
		picture = "\dayz_equip\textures\equip_toolbox_ca.paa";
		descriptionShort = $STR_EQUIP_DESC_2;
	};

	class ItemEtool : ItemCore {
		scope = public;
		displayName = $STR_EQUIP_NAME_1;
		model = "\dayz_equip\models\etool.p3d";
		picture = "\dayz_equip\textures\equip_etool_ca.paa";
		descriptionShort = $STR_EQUIP_DESC_1;
	};
	
	class ItemMatchbox : ItemCore {
		scope = public;
		displayName = $STR_EQUIP_NAME_3;
		model = "\dayz_equip\models\matchbox_gear.p3d";
		picture = "\dayz_equip\textures\equip_matchbox_ca.paa";
		descriptionShort = $STR_EQUIP_DESC_3;
		
		class ItemActions {
			class Use {
				text = $STR_ACTIONS_LIGHTFIRE;
				script = "spawn player_makeFire;";
				use[] = {"PartWoodPile"};
			};
		};
	};
	
	class ItemHatchet : ItemCore {
		scope = public;
		displayName = $STR_EQUIP_NAME_41;
		model = "\dayz_equip\models\hatchet.p3d";
		picture = "\dayz_equip\textures\equip_hatchet_CA.paa";
		descriptionShort = $STR_EQUIP_DESC_41;
		
		class ItemActions {
			class Use {
				text = $STR_ACTIONS_CHOPWOOD;
				script = "spawn player_chopWood;";
			};
			
			class Toolbelt {
				text = "Remove from Toolbelt";
				script = "spawn player_addToolbelt;";
				use[] = {"ItemHatchet"};
				output[] = {"MeleeHatchet"};
			};
		};
	};

	class ItemCrowbar : ItemCore {
		scope = public;
		displayName = $STR_EQUIP_NAME_47;
		model = "\dayz_equip\models\crowbar.p3d";
		picture = "\dayz_equip\textures\equip_crowbar_CA.paa";
		descriptionShort = $STR_EQUIP_DESC_47;
		
		class ItemActions {
			class Toolbelt {
				text = "Remove from Toolbelt";
				script = "spawn player_addToolbelt;";
				use[] = {"ItemCrowbar"};
				output[] = {"MeleeCrowbar"};
			};
		};
	};
	
	class ItemKnife : ItemCore {
		scope = public;
		displayName = $STR_EQUIP_NAME_4;
		model = "\dayz_equip\models\knife_gear.p3d";
		picture = "\dayz_equip\textures\equip_knife_ca.paa";
		descriptionShort = $STR_EQUIP_DESC_4;
	};
	
	class ItemFlashlight : ItemCore {
		scope = public;
		displayName = $STR_EQUIP_NAME_5;
		model = "\dayz_equip\models\flashlight.p3d";
		picture = "\dayz_equip\textures\equip_flashlight_ca.paa";
		descriptionShort = $STR_EQUIP_DESC_5;
		
		class ItemActions {
			class Toolbelt {
				text = "Remove from toolbelt";
				script = "spawn player_addToolbelt;";
				use[] = {"ItemFlashlight"};
				output[] = {"MeleeFlashlight"};
			};
		};
	};
	class Pistol;	// External class reference
	
	class MeleeFlashlight : Pistol {
		scope = public;
		canDrop = false;
		model = "\dayz_equip\models\flashlight.p3d";
		modelOptics = "-";
		picture = "\dayz_equip\textures\equip_flashlight_ca.paa";
		magazines[] = {};
		displayName = $STR_EQUIP_NAME_5;
		begin1[] = {};
		begin2[] = {};
		soundBegin[] = {"begin1", 0.5, "begin2", 0.5};
		reloadMagazineSound[] = {};
		recoil = "recoil_single_pistol_2outof3";
		recoilProne = "recoil_single_pistol_prone_2outof3";
		distanceZoomMin = 50;
		distanceZoomMax = 50;
		
		class Library {
			libTextDesc = "A flashlight (or torch in British English) is a hand-held portable electric-powered light source. Usually the light source is a small incandescent light bulb or light-emitting diode (LED).";
		};
		descriptionShort = $STR_EQUIP_DESC_5;
		autoFire = false;
		
		class FlashLight {
			color[] = {0.9, 0.9, 0.7, 0.9};
			ambient[] = {0.1, 0.1, 0.1, 1};
			position = "flash dir";
			direction = "flash";
			angle = 30;
			scale[] = {1, 1, 0.5};
			brightness = 0.1;
		};
		
		class ItemActions {
			class Toolbelt {
				text = "Add to toolbelt";
				script = "spawn player_addToolbelt;";
				use[] = {"MeleeFlashlight"};
				output[] = {"ItemFlashlight"};
			};
		};
		minRange = 0;
		minRangeProbab = 0.1;
		midRange = 30;
		midRangeProbab = 0.3;
		maxRange = 50;
		maxRangeProbab = 0.04;
	};
	
	class MeleeFlashlightRed : MeleeFlashlight {
		model = "\dayz_equip\models\flashlight_mil.p3d";
		picture = "\dayz_equip\textures\equip_flashlight_mil_ca.paa";
		displayName = $STR_EQUIP_NAME_6;
		descriptionShort = $STR_EQUIP_DESC_6;
		
		class FlashLight {
			color[] = {0.9, 0.0, 0.0, 0.9};
			ambient[] = {0.1, 0.0, 0.0, 1};
			position = "flash dir";
			direction = "flash";
			angle = 30;
			scale[] = {1, 1, 0.5};
			brightness = 0.08;
		};
		
		class ItemActions {
			class Toolbelt {
				text = "Add to toolbelt";
				script = "spawn player_addToolbelt;";
				use[] = {"MeleeFlashlightRed"};
				output[] = {"ItemFlashlightRed"};
			};
		};
	};
	
	class ItemFlashlightRed : ItemCore {
		scope = public;
		model = "\dayz_equip\models\flashlight_mil.p3d";
		picture = "\dayz_equip\textures\equip_flashlight_mil_ca.paa";
		displayName = $STR_EQUIP_NAME_6;
		descriptionShort = $STR_EQUIP_DESC_6;
		
		class ItemActions {
			class Toolbelt {
				text = "Remove from toolbelt";
				script = "spawn player_addToolbelt;";
				use[] = {"ItemFlashlightRed"};
				output[] = {"MeleeFlashlightRed"};
			};
		};
	};
};
