// config.bin - 17:27:18 09/25/12, generated in 0.10 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Enabled, Automatic comments: Enabled

#define ReadAndWrite		0
#define ReadAndCreate		1
#define ReadOnly		2
#define ReadOnlyVerified		3

#define VSoft		0
#define VArmor		1
#define VAir		2

#define private		0
#define protected		1
#define public		2

#define true	1
#define false	0

#include "CfgPatches.hpp"
#include "CfgVehicleClasses.hpp"
#include "RscStandardDisplay.hpp"
#include "RscObject.hpp"
#include "RscPicture.hpp"
#include "RscButton.hpp"
#include "RscButtonPhone.hpp"
#include "RscPhonePicture.hpp"
#include "CfgCloudlets.hpp"
#include "GlassSmash.hpp"
#include "RscPhoneDisplay.hpp"
#include "cfgWeapons.hpp"
#include "CfgMagazines.hpp"
#include "CfgVehicles.hpp"
#include "CfgSounds.hpp"
