// Generated by unRap v1.06 by Kegetys

class RscButtonPhone : RscButton {
	colorText[] = {0.543, 0.5742, 0.4102, 0};
	colorDisabled[] = {0.4, 0.4, 0.4, 0};
	colorBackground[] = {1, 0.537, 0, 0};
	colorBackgroundDisabled[] = {0.95, 0.95, 0.95, 0};
	colorBackgroundActive[] = {1, 0.537, 0, 0};
	colorFocused[] = {1, 0.537, 0, 0};
	colorShadow[] = {0.023529, 0, 0.0313725, 0};
	colorBorder[] = {0.023529, 0, 0.0313725, 0};
	soundEnter[] = {"", 0.09, 1};
	soundPush[] = {"", 0.09, 1};
	soundClick[] = {"", 0.07, 1};
	soundEscape[] = {"", 0.09, 1};
};
