// Generated by unRap v1.06 by Kegetys

class CfgActions {
	class None; // External class reference

	class TakeBag : None {
		show = 0;
	};

	class Rearm : None {
		show = 0;
	};
	class HideBody : None {
		show = 0;
	};
	/*
	class Gear : None {
		show = 0;
	};
	*/
};
