// Generated by unRap v1.06 by Kegetys

class CfgAddons {
	access = ReadAndCreate;
	
	class PreloadBanks {};
	
	class PreloadAddons {
		class dayz {
			list[] = {"dayz_code", "dayz", "dayz_equip", "dayz_weapons"};
		};
	};
};
