// Generated by unRap v1.06 by Kegetys

class CfgDifficulties {

	class Recruit {
		displayName = $STR_XBOX_DIFF_RECRUIT;
		description = "";
		showCadetHints = 1;
		showCadetWP = 1;
		maxPilotHeight = 150;
		scoreImage = "\ca\ui\textures\deb_pecka.paa";
		scoreChar = "o";
		badScoreImage = "\ca\ui\textures\deb_krizek.paa";
		badScoreChar = "X";
		skillFriendly = 1;
		precisionFriendly = 1;
		skillEnemy = 0.55;
		precisionEnemy = 0.3;
		myArmorCoef = 4.0;
		groupArmorCoef = 4.0;
		autoAimSizeFactor = 0.8;
		autoAimDistance = 1.2;
		autoAimAngle = 7;
		peripheralVisionAid = 0;
		visionAid = 0;
		
		class Flags {
			armor[] = {0, 0};
			friendlyTag[] = {0, 0};
			enemyTag[] = {0, 0};
			hud[] = {0, 0};
			hudPerm[] = {0, 0};
			hudWp[] = {0, 0};
			hudWpPerm[] = {0, 0};
			autoSpot[] = {0, 0};
			map[] = {0, 0};
			weaponCursor[] = {0, 0};
			autoGuideAT[] = {0, 0};
			clockIndicator[] = {0, 0};
			3rdPersonView[] = {0, 1};
			tracers[] = {0, 0};
			ultraAI[] = {0, 0};
			autoAim[] = {0, 0};
			unlimitedSaves[] = {0, 0};
			hudGroupInfo[] = {0, 0};
		};
	};
	
	class Regular {
		scoreImage = "\ca\ui\textures\deb_pecka.paa";
		badScoreImage = "\ca\ui\textures\deb_krizek.paa";
		skillFriendly = 1;
		precisionFriendly = 1;
		skillEnemy = 0.7;
		precisionEnemy = 0.5;
		myArmorCoef = 3.0;
		groupArmorCoef = 2.4;
		autoAimSizeFactor = 0.9;
		autoAimDistance = 1.3;
		autoAimAngle = 6;
		peripheralVisionAid = 0;
		visionAid = 0;
		
		class Flags {
			armor[] = {0, 0};
			friendlyTag[] = {0, 0};
			enemyTag[] = {0, 0};
			hud[] = {0, 0};
			hudPerm[] = {0, 0};
			hudWp[] = {0, 0};
			hudWpPerm[] = {0, 0};
			autoSpot[] = {0, 0};
			map[] = {0, 0};
			weaponCursor[] = {0, 0};
			autoGuideAT[] = {0, 0};
			clockIndicator[] = {0, 0};
			3rdPersonView[] = {0, 1};
			tracers[] = {0, 0};
			ultraAI[] = {0, 0};
			autoAim[] = {0, 0};
			unlimitedSaves[] = {0, 0};
			hudGroupInfo[] = {0, 0};
		};
	};
	
	class Veteran {
		scoreImage = "\ca\ui\textures\deb_hvezdicka.paa";
		badScoreImage = "\ca\ui\textures\deb_krizek.paa";
		skillFriendly = 1.0;
		precisionFriendly = 1.0;
		skillEnemy = 0.9;
		precisionEnemy = 0.75;
		myArmorCoef = 1.0;
		groupArmorCoef = 1.0;
		autoAimSizeFactor = 0.3;
		autoAimDistance = 0.6;
		autoAimAngle = 2.5;
		peripheralVisionAid = 0;
		visionAid = 0.0;
		
		class Flags {
			armor[] = {0, 0};
			friendlyTag[] = {0, 0};
			enemyTag[] = {0, 0};
			hud[] = {0, 0};
			hudPerm[] = {0, 0};
			hudWp[] = {0, 0};
			hudWpPerm[] = {0, 0};
			autoSpot[] = {0, 0};
			map[] = {0, 0};
			weaponCursor[] = {0, 0};
			autoGuideAT[] = {0, 0};
			clockIndicator[] = {0, 0};
			3rdPersonView[] = {0, 1};
			tracers[] = {0, 0};
			ultraAI[] = {0, 0};
			autoAim[] = {0, 0};
			unlimitedSaves[] = {0, 0};
			hudGroupInfo[] = {0, 0};
		};
	};

	class Mercenary {
		displayName = $STR_SKILL_EXPERT;
		description = "The most realistic settings possible: no 3rd person view, no articial help.";
		showCadetHints = 0;
		showCadetWP = 0;
		maxPilotHeight = 10000;
		scoreChar = "*";
		badScoreChar = "X";
		scoreImage = "\ca\ui\textures\deb_hvezdicka.paa";
		badScoreImage = "\ca\ui\textures\deb_krizek.paa";
		skillFriendly = 1.0;
		precisionFriendly = 1.0;
		skillEnemy = 1.0;
		precisionEnemy = 1.0;
		myArmorCoef = 1.0;
		groupArmorCoef = 1.0;
		autoAimSizeFactor = 0.3;
		autoAimDistance = 0.6;
		autoAimAngle = 2.5;
		peripheralVisionAid = 0;
		visionAid = 0;
		
		class Flags {
			armor[] = {0, 0};
			friendlyTag[] = {0, 0};
			enemyTag[] = {0, 0};
			hud[] = {0, 0};
			hudPerm[] = {0, 0};
			hudWp[] = {0, 0};
			hudWpPerm[] = {0, 0};
			autoSpot[] = {0, 0};
			map[] = {0, 0};
			weaponCursor[] = {0, 0};
			autoGuideAT[] = {0, 0};
			clockIndicator[] = {0, 0};
			3rdPersonView[] = {0, 1};
			tracers[] = {0, 0};
			ultraAI[] = {0, 0};
			autoAim[] = {0, 0};
			unlimitedSaves[] = {0, 0};
			deathMessages[] = {0, 1};
			netStats[] = {0, 1};
			vonID[] = {0, 1};
			hudGroupInfo[] = {0, 0};
		};
	};

};
