// Generated by unRap v1.06 by Kegetys

class CfgMovesAnimalsBase {
	class ManActions;	// External class reference
	class StandBase;	// External class reference
	class DefaultDie;	// External class reference
	class BlendAnims;	// External class reference
};
