// Generated by unRap v1.06 by Kegetys

class CfgMovesDogDZ : CfgMovesDogBase {
	primaryActionMaps[] = {"DogActions", "NoActions"};
	skeletonName = "DogSkeleton";
	gestures = "CfgGesturesDogDZ";
	
	class States {
		class Dog_Stop : StandBase {
			actions = "DogActions";
			duty = -1;
			file = "\CA\animals2\dogs\data\Anim\dogStop";
			speed = 1e+010;
			relSpeedMin = 0.7;
			relSpeedMax = 1.1;
			looped = true;
			ConnectTo[] = {"Dog_TurnR", 0.1, "Dog_StopV2", 0.1, "Dog_StopV1", 0.1, "Dog_TurnL", 0.1, "Dog_Sprint", 0.02, "Dog_Run", 0.02, "Dog_Walk", 0.2};
			InterpolateTo[] = {"Dog_TurnR", 0.1, "Dog_Die", 0.02, "Dog_TurnL", 0.1, "Dog_Sprint", 0.02, "Dog_Run", 0.02, "Dog_Walk", 0.2};
		};
		
		class Dog_TurnL : Dog_Stop {
			file = "\CA\animals2\Dogs\data\anim\dog_rotateL.rtm";
			speed = 1;
			ConnectTo[] = {"Dog_Stop", 0.1};
			InterpolateTo[] = {"Dog_Stop", 0.1};
		};
		
		class Dog_TurnR : Dog_TurnL {
			file = "\CA\animals2\Dogs\data\anim\dog_rotateR.rtm";
			ConnectTo[] = {"Dog_Stop", 0.1};
			InterpolateTo[] = {"Dog_Stop", 0.1};
		};
		
		class Dog_StopV1 : Dog_Stop {
			file = "\CA\animals2\dogs\data\Anim\dogIDLE";
			speed = 2.14;
			variantAfter[] = {5, 7, 10};
			looped = false;
			ConnectTo[] = {"Dog_Stop", 0.1};
			InterpolateTo[] = {"Dog_Die", 0.02};
		};
		
		class Dog_StopV2 : Dog_Stop {
			file = "\CA\animals2\dogs\data\Anim\dogBark";
			speed = 1;
			variantAfter[] = {1, 1, 1};
			looped = false;
			ConnectTo[] = {"Dog_Stop", 0.1};
			InterpolateTo[] = {"Dog_Die", 0.02};
		};
		
		class Dog_Attack : Dog_Stop {
			file = "\CA\animals2\dogs\data\Anim\dogAttack";
			speed = 1;
			variantAfter[] = {1, 1, 1};
			looped = false;
			ConnectTo[] = {"Dog_Stop", 0.1};
			InterpolateTo[] = {"Dog_Die", 0.02};
		};
		
		class Dog_SitDown : Dog_Stop {
			actions = "DogSit";
			file = "\CA\animals2\dogs\data\Anim\dogSit1In";
			speed = 1.43;
			variantAfter[] = {1, 1, 1};
			looped = false;
			relSpeedMin = 0.996672;
			relSpeedMax = 0.996672;
			ConnectTo[] = {};
			InterpolateTo[] = {"Dog_Die", 0.02};
		};
		
		class Dog_Siting : Dog_Stop {
			actions = "DogSit";
			file = "\CA\animals2\dogs\data\Anim\dogSit2Idle";
			speed = 1.58;
			variantAfter[] = {1, 1, 1};
			looped = true;
			ConnectTo[] = {};
			InterpolateTo[] = {"Dog_Die", 0.02};
		};
		
		class Dog_SitUp : Dog_Stop {
			actions = "DogSit";
			file = "\CA\animals2\dogs\data\Anim\dogSit3Out";
			speed = 1.08;
			variantAfter[] = {1, 1, 1};
			looped = false;
			relSpeedMin = 0.996672;
			relSpeedMax = 0.996672;
			ConnectTo[] = {"Dog_Stop", 0.1, "Dog_Run", 0.1, "Dog_Walk", 0.1, "Dog_Sprint", 0.1};
			InterpolateTo[] = {"Dog_Die", 0.02, "Dog_Run", 0.1, "Dog_Walk", 0.1, "Dog_Sprint", 0.1};
		};
		
		class Dog_Sprint : Dog_Stop {
			actions = "DogSprint";
			file = "\CA\animals2\dogs\data\Anim\dogSprint";
			duty = 0.5;
			speed = 4.5;
			ConnectTo[] = {"Dog_Stop", 0.02, "Dog_Run", 0.02, "Dog_Walk", 0.02};
			InterpolateTo[] = {"Dog_Die", 0.02, "Dog_Stop", 0.02, "Dog_Run", 0.02, "Dog_Walk", 0.02};
		};
		
		class Dog_Run : Dog_Stop {
			file = "\CA\animals2\dogs\data\Anim\dogRun";
			duty = -0.5;
			speed = 1.8;
			ConnectTo[] = {"Dog_Stop", 0.02, "Dog_Sprint", 0.02, "Dog_Walk", 0.02};
			InterpolateTo[] = {"Dog_Die", 0.02, "Dog_Stop", 0.02, "Dog_Sprint", 0.02, "Dog_Walk", 0.02};
		};
		
		class Dog_Walk : Dog_Stop {
			duty = -0.7;
			file = "\CA\animals2\dogs\data\Anim\dogWalk";
			speed = 1.3;
			variantAfter[] = {3, 10, 20};
			ConnectTo[] = {"Dog_Stop", 0.2, "Dog_Sprint", 0.2, "Dog_Run", 0.2};
			InterpolateTo[] = {"Dog_Die", 0.02, "Dog_Stop", 0.2, "Dog_Sprint", 0.2, "Dog_Run", 0.2};
		};
		
		class Dog_Die : DefaultDie {
			enableDirectControl = 0;
			actions = "NoActions";
			file = "\CA\animals2\dogs\data\Anim\dogDeath";
			speed = 1.2;
			looped = false;
			variantsPlayer[] = {};
			variantsAI[] = {""};
			variantAfter[] = {0, 0, 0};
			terminal = true;
			soundEnabled = false;
			ConnectTo[] = {};
			InterpolateTo[] = {};
		};
	};
	
	class Actions {
		class NoActions : ManActions {
			turnSpeed = 8;
			limitFast = 5.5;
			useFastMove = 0;
			upDegree = 0;
			GestureBark[] = {"GestureBark", "Gesture"};
			GestureIdle1[] = {"GestureIdle1", "Gesture"};
			GestureIdle2[] = {"GestureIdle2", "Gesture"};
			GestureSniff[] = {"GestureSniff", "Gesture"};
		};
		
		class DogActions : NoActions {
			Stop = "Dog_Stop";
			StopRelaxed = "Dog_Stop";
			TurnL = "Dog_TurnL";
			TurnR = "Dog_TurnR";
			TurnLRelaxed = "Dog_TurnL";
			TurnRRelaxed = "Dog_TurnR";
			Default = "Dog_Stop";
			JumpOff = "Dog_Stop";
			WalkF = "Dog_Walk";
			SlowF = "Dog_Run";
			FastF = "Dog_Sprint";
			EvasiveForward = "Dog_Sprint";
			Down = "Dog_Stop";
			Up = "Dog_Stop";
			PlayerStand = "Dog_Stop";
			PlayerProne = "Dog_Stop";
			PlayerCrouch = "";
			Crouch = "";
			Lying = "Dog_Stop";
			Stand = "Dog_Stop";
			Combat = "Dog_Stop";
			CanNotMove = "Dog_Stop";
			Civil = "Dog_Stop";
			CivilLying = "Dog_Stop";
			FireNotPossible = "Dog_StopV1";
			Die = "Dog_Die";
			turnSpeed = 8;
			limitFast = 5.5;
			useFastMove = 0;
			upDegree = "ManPosNoWeapon";
			StartSwim = "Dog_Die";
		};
		
		class DogSprint : DogActions {
			Die = "Dog_Die";
			turnSpeed = 4;
			limitFast = 5.5;
			useFastMove = 1;
		};
		
		class DogSit : NoActions {
			Up = "Dog_Stop";
			PlayerStand = "Dog_Stop";
			Stand = "Dog_Stop";
			WalkF = "Dog_Walk";
			SlowF = "Dog_Run";
			FastF = "Dog_Sprint";
			EvasiveForward = "Dog_Sprint";
			PlayerCrouch = "Dog_Stop";
			Crouch = "Dog_Stop";
			Die = "Dog_Die";
			upDegree = "ManPosNoWeapon";
			StartSwim = "Dog_Die";
		};
	};
	
	class Interpolations {};
	transitionsInterpolated[] = {};
	transitionsSimple[] = {};
	transitionsDisabled[] = {};
	
	class BlendAnims : BlendAnims {
		aimingDefault[] = {"head", 1, "Jaw", 1, "Neck1", 0.5, "Tongue1", 1, "Tongue2", 1};
		untiltWeaponDefault[] = {};
		legsDefault[] = {};
		headDefault[] = {"head", 1, "Jaw", 1, "Neck1", 0.5, "Tongue1", 1, "Tongue2", 1};
		aimingNo[] = {};
		legsNo[] = {};
		headNo[] = {};
		aimingUpDefault[] = {};
	};
};
