// Generated by unRap v1.06 by Kegetys

class CfgMods {
	class DayZ {
		dir = "DayZ";
		name = "DayZ Redux";
		picture = "z\addons\dayz_code\gui\dayz_logo_ca.paa";
		hidePicture = 0;
		hideName = 0;
		action = "http://www.dayzredux.com";
		version = 1.0.0;
		hiveVersion = 0.96;
	};
};
