// Generated by unRap v1.06 by Kegetys
class CfgPatches {
	class dayz_code {
		units[] = {};
		weapons[] = {};
		requiredVersion = 0.1;
		requiredAddons[] = {"dayz_equip", "dayz_weapons", "CAMisc3", "CABuildingParts", "CABuildingParts_Signs", "CAStructuresHouse", "CAStructuresLand_Ind_Stack_Big", "CAStructures_Misc_Powerlines", "CAStructures", "CABuildings", "CABuildings2", "Ind_MalyKomin", "CAStructures_A_CraneCon", "CAStructures_Mil", "CAStructures_Nav", "CAStructures_Rail", "A_Crane_02", "A_TVTower", "CAStructures_Railway", "CAStructuresHouse", "CAStructuresHouse_HouseBT"};
	};
};
