// Generated by unRap v1.06 by Kegetys

class CfgSurvival {
	class Inventory {
		class Default {
			magazines[] = {"ItemBandage", "ItemPainkiller"};
			weapons[] = {"ItemFlashlight"};
			backpackWeapon = "";
			backpack = "";
		};
	};
	
	class Meat {
		class Default {
			yield = 2;
		};
		
		class Cow : Default {
			yield = 8;
		};
		
		class Cow01 : Cow {};
		
		class Cow02 : Cow {};
		
		class Cow03 : Cow {};
		
		class Cow04 : Cow {};
		
		class Goat : Default {
			yield = 3;
		};
		
		class Sheep : Default {
			yield = 5;
		};
		
		class WildBoar : Default {
			yield = 4;
		};
	};
};
