// config.bin - 17:57:58 09/20/12, generated in 0.21 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Enabled, Automatic comments: Enabled

#define ReadAndWrite		0
#define ReadAndCreate		1
#define ReadOnly		2
#define ReadOnlyVerified		3

#define VSoft		0
#define VArmor		1
#define VAir		2

#define true	1
#define false	0

#define private		0
#define protected		1
#define public		2

#define TEast		0
#define TWest		1
#define TGuerrila		2
#define TCivilian		3
#define TSideUnknown		4
#define TEnemy		5
#define TFriendly		6
#define TLogic		7

// The default template provided by BIS
// Control types
#define CT_STATIC           0
#define CT_BUTTON           1
#define CT_EDIT             2
#define CT_SLIDER           3
#define CT_COMBO            4
#define CT_LISTBOX          5
#define CT_TOOLBOX          6
#define CT_CHECKBOXES       7
#define CT_PROGRESS         8
#define CT_HTML             9
#define CT_STATIC_SKEW      10
#define CT_ACTIVETEXT       11
#define CT_TREE             12
#define CT_STRUCTURED_TEXT  13
#define CT_CONTEXT_MENU     14
#define CT_CONTROLS_GROUP   15
#define CT_XKEYDESC         40
#define CT_XBUTTON          41
#define CT_XLISTBOX         42
#define CT_XSLIDER          43
#define CT_XCOMBO           44
#define CT_ANIMATED_TEXTURE 45
#define CT_OBJECT           80
#define CT_OBJECT_ZOOM      81
#define CT_OBJECT_CONTAINER 82
#define CT_OBJECT_CONT_ANIM 83
#define CT_LINEBREAK        98
#define CT_USER             99
#define CT_MAP              100
#define CT_MAP_MAIN         101
// Static styles
#define ST_POS            0x0F
#define ST_HPOS           0x03
#define ST_VPOS           0x0C
#define ST_LEFT           0x00
#define ST_RIGHT          0x01
#define ST_CENTER         0x02
#define ST_DOWN           0x04
#define ST_UP             0x08
#define ST_VCENTER        0x0c
#define ST_TYPE           0xF0
#define ST_SINGLE         0
#define ST_MULTI          16
#define ST_TITLE_BAR      32
#define ST_PICTURE        48
#define ST_FRAME          64
#define ST_BACKGROUND     80
#define ST_GROUP_BOX      96
#define ST_GROUP_BOX2     112
#define ST_HUD_BACKGROUND 128
#define ST_TILE_PICTURE   144
#define ST_WITH_RECT      160
#define ST_LINE           176
#define ST_KEEP_ASPECT_RATIO	0x800

enum {
	DESTRUCTENGINE = 2,
	DESTRUCTDEFAULT = 6,
	DESTRUCTWRECK = 7,
	DESTRUCTTREE = 3,
	DESTRUCTTENT = 4,
	DESTRUCTNO = 0,
	DESTRUCTMAN = 5,
	DESTRUCTBUILDING = 1,
};

#include "CfgPatches.hpp"
#include "CfgMods.hpp"
#include "CfgAddons.hpp"
#include "RscPictureGUI.hpp"
#include "RscStructuredText.hpp"
#include "RscStructuredTextGUI.hpp"
#include "CfgMovesAnimalsBase.hpp"
#include "CfgMovesDogBase.hpp"
#include "CfgMovesDogDZ.hpp"
#include "CfgGesturesDogDZ.hpp"
class RscPicture;	// External class reference
class RscButton;	// External class reference
//class RscShortcutButton;	// External class reference
#include "RscShortcutButton.hpp"
class CA_IGUI_Title;	// External class reference
class RscText;	// External class reference
class RscControlsGroup;	// External class reference
class RscLineBreak;	// External class reference
class RscIGUIShortcutButton;	// External class reference
//#include "RscIGUIShortcutButton.hpp"
class RscGearShortcutButton;	// External class reference
//#include "RscGearShortcutButton.hpp"
class RscListNBox;	// External class reference
//class RscIGUIListNBox;	// External class reference
#include "RscIGUIListNBox.hpp"
class RscActiveText;	// External class reference
class RscPictureKeepAspect;	// External class reference
class RscStandardDisplay;	// External class reference
class RscProgress;	// External class reference
class RscProgressNotFreeze;	// External class reference
class RscButtonTextOnly;	// External class reference
#include "RscDisplayLoading.hpp"
#include "RscDisplayStart.hpp"
class CA_TextLanguage;	// External class reference
class RscXListBox;	// External class reference
#include "RscDisplayGameOptions.hpp"
#include "RscDisplayMain.hpp"
#include "RscButtonActionMenu.hpp"
#include "RscDisplayGenderSelect.hpp"
#include "RscVehicleInspection.hpp"
#include "RscDisplayGear.hpp"
#include "DZ_ItemInteraction.hpp"
#include "RscTitles.hpp"
#include "CfgDifficulties.hpp"
#include "CfgVehicles.hpp"
#include "CfgNonAIVehicles.hpp"
#include "CfgLoot.hpp"
#include "CfgSurvival.hpp"
#include "CfgBuildingLoot.hpp"
#include "CfgChernarusRedux.hpp"
#include "RscDisplayDSinterface.hpp"
class CA_Title; // External class reference
class RscIGUIListBox; // External class reference
#include "RscDisplayMultiplayerSetup.hpp"
class RscShortcutButtonMain; // External class reference
#include "RscDisplayMPInterrupt.hpp"
class CA_Black_Back; // External class reference
class RscMapControl; // External class reference
class IGUIBack; // External class reference
class RscIGUIText; // External class reference
class RscHTML; // External class reference
class RscObject; // External class reference
#include "RscDisplayMainMap.hpp"
class RscIGText; // External class reference
#include "RscDisplayDiary.hpp"
#include "CfgActions.hpp"