// Generated by unRap v1.06 by Kegetys

class RscButtonActionMenu : RscButton {
	SizeEx = 0.02674;
	colorBackground[] = {0.44, 0.7, 0.44, 1};
	colorBackgroundActive[] = {0.24, 0.5, 0.24, 1};
	colorBackgroundDisabled[] = {1, 1, 1, 0};
	colorFocused[] = {0.2, 0.5, 0.2, 1};
	colorShadow[] = {1, 1, 1, 0};
	borderSize = 0;
	w = "0.095 * safezoneW";
	h = "0.025 * safezoneH";
};
