// Generated by unRap v1.06 by Kegetys

class RscDisplayMain : RscStandardDisplay {
	class controlsBackground {
		class Mainback;	// External class reference
		
		class CA_ARMA2 : RscPicture {
			text = "z\addons\dayz_code\gui\dayz_logo_ca.paa";
		};
	};
	onLoad = "((_this select 0) displayCtrl 138) ctrlEnable false;";
	
	class controls {
		class CA_Version;	// External class reference
		
		class DAYZ_Version : CA_Version {
			idc = -1;
			text = "DayZ Redux 1.0.0";
			y = "(SafeZoneH + SafeZoneY) - (1 - 0.95)";
		};
		class CA_TitleMainMenu;	// External class reference
		class CA_SinglePlayer;	// External class reference
		class CA_MP;	// External class reference
		class CA_Options;	// External class reference
		class CA_PlayerProfile;	// External class reference
		class CA_Expansions;	// External class reference
		class CA_Exit;	// External class reference
	};
};
