// Generated by unRap v1.06 by Kegetys

class RscDisplayGenderSelect {
	idd = 6902;
	enableDisplay = 1;
	
	class controls {
		class RscText_1000 : RscText {
			idc = 1000;
			x = 0.455592;
			y = 0.200908;
			w = 0.1;
			h = 0.1;
		};
		
		class RscButton_1600 : RscButton {
			idc = 1600;
			text = $STR_UI_GENDER_MALE;
			x = "0.400884 * safezoneW + safezoneX";
			y = "0.593966 * safezoneH + safezoneY";
			w = "0.0881029 * safezoneW";
			h = "0.0469831 * safezoneH";
			onButtonClick = "closeDialog 0;dayz_selectGender = 'S2_RX';";
		};
		
		class RscButton_1601 : RscButton {
			idc = 1601;
			text = $STR_UI_GENDER_FEMALE;
			x = "0.511013 * safezoneW + safezoneX";
			y = "0.593966 * safezoneH + safezoneY";
			w = "0.0881029 * safezoneW";
			h = "0.0469831 * safezoneH";
			onButtonClick = "closeDialog 0;dayz_selectGender = 'SW2_RX';";
		};
		
		class RscText_1001 : RscText {
			idc = 1001;
			text = $STR_UI_GENDER_TITLE;
			x = "0.400884 * safezoneW + safezoneX";
			y = "0.394288 * safezoneH + safezoneY";
			w = "0.198231 * safezoneW";
			h = "0.0352373 * safezoneH";
		};
		
		class RscStructuredText_1100 : RscStructuredText {
			idc = 1100;
			text = $STR_UI_GENDER_DESC;
			x = "0.400884 * safezoneW + safezoneX";
			y = "0.453017 * safezoneH + safezoneY";
			w = "0.198231 * safezoneW";
			h = "0.117458 * safezoneH";
			colorBackground[] = {-1, -1, -1, 0};
		};
	};
};
