// Generated by unRap v1.06 by Kegetys

class RscDisplayLoading {
	class Variants {
		class LoadingOne {
			class controls {
				class LoadingPic : RscPictureKeepAspect {
					text = "z\addons\dayz_code\gui\dayz_logo_ca.paa";
				};
			};
		};
	};
};
