// Generated by unRap v1.06 by Kegetys

class RscGearShortcutButton : RscShortcutButton {
	w = 0.0392157;
	h = 0.0522876;
	style = 2;
	color[] = {1, 1, 1, 1};
	color2[] = {1, 1, 1, 0.85};
	colorBackground[] = {1, 1, 1, 1};
	colorbackground2[] = {1, 1, 1, 0.85};
	colorDisabled[] = {1, 1, 1, 0.4};
	
	class HitZone {
		left = 0.0;
		top = 0.0;
		right = 0.0;
		bottom = 0.0;
	};
	
	class ShortcutPos {
		left = -0.006;
		top = -0.007;
		w = 0.0392157;
		h = 0.0522876;
	};
	
	class TextPos {
		left = 0.003;
		top = 0.001;
		right = 0.0;
		bottom = 0.0;
	};
	sizeEx = 0.1;
	animTextureNormal = "\ca\ui\data\igui_gear_normal_ca.paa";
	animTextureDisabled = "\ca\ui\data\igui_gear_disabled_ca.paa";
	//animTextureOver = "\ca\ui\data\igui_gear_over_ca.paa";
	animTextureOver = "\z\addons\dayz_code\ui\igui_gear_over_ca.paa";
	//animTextureFocused = "\ca\ui\data\igui_gear_focus_ca.paa";
	animTextureFocused = "\z\addons\dayz_code\ui\igui_gear_focus_ca.paa";
	animTexturePressed = "\ca\ui\data\igui_gear_down_ca.paa";
	animTextureDefault = "\ca\ui\data\igui_gear_normal_ca.paa";
	
	class Attributes {
		font = "Zeppelin32";
		color = "#E5E5E5";
		align = "center";
		shadow = "false";
	};
};
