// Generated by unRap v1.06 by Kegetys

class RscIGUIListNBox : RscListNBox {
	style = 0 + 0x10;
	shadow = 2;
	color[] = {1, 1, 1, 1};
	colorText[] = {1, 1, 1, 0.75};
	colorScrollbar[] = {0.95, 0.95, 0.95, 1};
	colorSelect[] = {0.95, 0.95, 0.95, 1};
	colorSelect2[] = {0.95, 0.95, 0.95, 1};
	//colorSelectBackground[] = {0.8784, 0.8471, 0.651, 1.0};
	//colorSelectBackground2[] = {0.8784, 0.8471, 0.651, 1.0};
	colorSelectBackground[] = {0.8, 0.8, 0.8, 1.0};
	colorSelectBackground2[] = {0.8, 0.8, 0.8, 1.0};
	period = 0;
	colorBackground[] = {0, 0, 0, 1};
	columns[] = {0.1, 0.7, 0.1, 0.1};
	
	class ScrollBar {
		color[] = {1, 1, 1, 0.6};
		colorActive[] = {1, 1, 1, 1};
		colorDisabled[] = {1, 1, 1, 0.3};
		thumb = "\ca\ui\data\igui_scrollbar_thumb_ca.paa";
		arrowFull = "\ca\ui\data\igui_arrow_top_active_ca.paa";
		arrowEmpty = "\ca\ui\data\igui_arrow_top_ca.paa";
		border = "\ca\ui\data\igui_border_scroll_ca.paa";
	};
};
