// Generated by unRap v1.06 by Kegetys

class RscStructuredTextGUI : RscStructuredText {
	colorBackground[] = {0, 0, 0, 0};
	colorText[] = {1, 1, 1, 1};
	
	class Attributes : Attributes {
		align = "center";
		valign = "middle";
	};
};
