// Generated by unRap v1.06 by Kegetys

class CfgAmmo {
	class FakeAmmo;	// External class reference
	
	class MissileCore : FakeAmmo {};
	
	class BombCore : FakeAmmo {};
	
	class LaserBombCore : FakeAmmo {};
	
	class RocketCore : FakeAmmo {};
	
	class ArtilleryRocketCore : FakeAmmo {};
	
	class ShellCore : FakeAmmo {};
	
	class B_127x108_APHE : FakeAmmo {};
	
	class B_145x115_AP : FakeAmmo {};
	
	class B_20mm_AP : FakeAmmo {};
	
	class B_20mm_AA : FakeAmmo {};
	
	class B_23mm_AA : FakeAmmo {};
	
	class B_23mm_HE : FakeAmmo {};
	
	class B_23mm_AP : FakeAmmo {};
	
	class B_23mm_APHE : FakeAmmo {};
	
	class B_25mm_HE : FakeAmmo {};
	
	class B_25mm_HEI : FakeAmmo {};
	
	class B_25mm_APDS : FakeAmmo {};
	
	class B_30mm_AP : FakeAmmo {};
	
	class B_30mmA10_AP : FakeAmmo {};
	
	class B_30mm_HE : FakeAmmo {};
	
	class B_30mm_AA : FakeAmmo {};
	
	class ShellBase : FakeAmmo {};
	
	class Sh_105_HE : FakeAmmo {};
	
	class Sh_100_HE : FakeAmmo {};
	
	class Sh_120_HE : FakeAmmo {};
	
	class Sh_120_SABOT : FakeAmmo {};
	
	class Sh_122_HE : FakeAmmo {};
	
	class Sh_125_HE : FakeAmmo {};
	
	class Sh_125_SABOT : FakeAmmo {};
	
	class Sh_85_HE : FakeAmmo {};
	
	class Sh_85_AP : FakeAmmo {};
	
	//class RocketBase : FakeAmmo {};
	
	class G_Camel_HE : FakeAmmo {};
	
	class R_Hydra_HE : FakeAmmo {};
	
	class R_57mm_HE : FakeAmmo {};
	
	class R_80mm_HE : FakeAmmo {};
	
	class R_S8T_AT : FakeAmmo {};
	
	//class R_M136_AT : FakeAmmo {};
	
	class R_RPG18_AT : FakeAmmo {};
	
	//class R_PG7V_AT : FakeAmmo {};
	
	class R_PG7VL_AT : FakeAmmo {};
	
	class R_PG7VR_AT : FakeAmmo {};
	
	class R_OG7_AT : FakeAmmo {};
	
	class R_PG9_AT : FakeAmmo {};
	
	class R_OG9_HE : FakeAmmo {};
	
	class R_SMAW_HEDP : FakeAmmo {};
	
	class R_SMAW_HEAA : FakeAmmo {};
	
	class R_GRAD : FakeAmmo {};
	
	class R_MLRS : FakeAmmo {};
	
	class MissileBase : FakeAmmo {};
	
	class M_Javelin_AT : FakeAmmo {};
	
	class M_Stinger_AA : FakeAmmo {};
	
	class M_Sidewinder_AA : FakeAmmo {};
	
	class M_Sidewinder_AA_F35 : FakeAmmo {};
	
	class M_Strela_AA : FakeAmmo {};
	
	class M_Igla_AA : FakeAmmo {};
	
	class M_AT5_AT : FakeAmmo {};
	
	class M_AT13_AT : FakeAmmo {};
	
	class M_TOW_AT : FakeAmmo {};
	
	class M_TOW2_AT : FakeAmmo {};
	
	class M_AT10_AT : FakeAmmo {};
	
	class M_AT11_AT : FakeAmmo {};
	
	class M_Hellfire_AT : FakeAmmo {};
	
	class M_Vikhr_AT : FakeAmmo {};
	
	class M_Maverick_AT : FakeAmmo {};
	
	class M_R73_AA : FakeAmmo {};
	
	class M_Ch29_AT : FakeAmmo {};
	
	class M_AT2_AT : FakeAmmo {};
	
	class M_AT6_AT : FakeAmmo {};
	
	class M_AT9_AT : FakeAmmo {};
	
	class M_9M311_AA : FakeAmmo {};
	
	class Bo_GBU12_LGB : FakeAmmo {};
	
	class Bo_GBU12_LGB_F35 : FakeAmmo {};
	
	class Bo_FAB_250 : FakeAmmo {};
	
	class Bo_Mk82 : FakeAmmo {};
	
	class B_30x113mm_M789_HEDP : FakeAmmo {};
	
	class ARTY_Sh_Base : FakeAmmo {};
	
	class ARTY_Flare_Small : FakeAmmo {};
	
	class ARTY_Flare_Medium : FakeAmmo {};
	
	class ARTY_Sh_Base_NET : FakeAmmo {};
	
	class ARTY_Sh_105_NET : FakeAmmo {};
	
	class ARTY_Sh_105_NET_NOFX : FakeAmmo {};
	
	class ARTY_Sh_105_LASNET : FakeAmmo {};
	
	class ARTY_Sh_122_NET : FakeAmmo {};
	
	class ARTY_Sh_122_NET_NOFX : FakeAmmo {};
	
	class ARTY_Sh_122_LASNET : FakeAmmo {};
	
	class ARTY_Sh_81_NET : FakeAmmo {};
	
	class ARTY_Sh_82_NET : FakeAmmo {};
	
	class ARTY_Sh_120_NET : FakeAmmo {};
	
	class ARTY_Sh_227_NET : FakeAmmo {};
	
	class ARTY_Sh_105_HE : FakeAmmo {};
	
	class ARTY_Sh_105_WP : FakeAmmo {};
	
	class ARTY_Sh_105_SADARM : FakeAmmo {};
	
	class ARTY_Sh_105_LASER : FakeAmmo {};
	
	class ARTY_Sh_105_ILLUM : FakeAmmo {};
	
	class ARTY_Sh_105_SMOKE : FakeAmmo {};
	
	class ARTY_Sh_81_HE : FakeAmmo {};
	
	class ARTY_Sh_81_WP : FakeAmmo {};
	
	class ARTY_Sh_81_ILLUM : FakeAmmo {};
	
	class ARTY_R_227mm_HE_Rocket : FakeAmmo {};
	
	class ARTY_R_227mm_HE : FakeAmmo {};
	
	class ARTY_Sh_122_HE : FakeAmmo {};
	
	class ARTY_Sh_122_WP : FakeAmmo {};
	
	class ARTY_Sh_122_SADARM : FakeAmmo {};
	
	class ARTY_Sh_122_LASER : FakeAmmo {};
	
	class ARTY_Sh_122_ILLUM : FakeAmmo {};
	
	class ARTY_Sh_122_SMOKE : FakeAmmo {};
	
	class ARTY_SADARM_PROJO : FakeAmmo {};
	
	class ARTY_SADARM_NET : FakeAmmo {};
	
	class ARTY_SADARM_BURST : FakeAmmo {};
	
	class ARTY_SmokeShellWhite : FakeAmmo {};
	
	class ARTY_Sh_82_HE : FakeAmmo {};
	
	class ARTY_Sh_82_WP : FakeAmmo {};
	
	class ARTY_Sh_82_ILLUM : FakeAmmo {};
	
	class ARTY_R_120mm_HE_Rocket : FakeAmmo {};
	
	class ARTY_R_120mm_HE : FakeAmmo {};
	
	class Warfare82mmMortar : FakeAmmo {};
	
	class M_NLAW_AT : FakeAmmo {};
	
	class Sh_40_HE : FakeAmmo {};
	
	class Sh_40_SABOT : FakeAmmo {};
	
	class M_CRV7_AT : FakeAmmo {};
	
	class M_CRV7_HEPD : FakeAmmo {};
	
	class M_CRV7_FAT : FakeAmmo {};
	
	class BAF_ied_v1 : FakeAmmo {};
	
	class BAF_ied_v2 : FakeAmmo {};
	
	class BAF_ied_v3 : FakeAmmo {};
	
	class BAF_ied_v4 : FakeAmmo {};
	
	class Sh_100_HEAT : FakeAmmo {};
	
	class Sh_105_HESH : FakeAmmo {};
	
	class Sh_105_APDS : FakeAmmo {};
	
	class R_MEEWS_HEDP : FakeAmmo {};
	
	class R_MEEWS_HEAT : FakeAmmo {};
	
	class ARTY_Sh_120_HE : FakeAmmo {};
	
	class Sh_81_HE : FakeAmmo {};
	
	class Sh_81_WP : FakeAmmo {};
	
	class Sh_81_ILLUM : FakeAmmo {};
	
	class Sh_82_HE : FakeAmmo {};
	
	class Sh_82_WP : FakeAmmo {};
	
	class Sh_82_ILLUM : FakeAmmo {};
	
	class Sh_122_WP : FakeAmmo {};
	
	class Sh_122_SADARM : FakeAmmo {};
	
	class Sh_122_LASER : FakeAmmo {};
	
	class Sh_122_ILLUM : FakeAmmo {};
	
	class Sh_122_SMOKE : FakeAmmo {};
	
	class Sh_105_WP : FakeAmmo {};
	
	class Sh_105_SADARM : FakeAmmo {};
	
	class Sh_105_LASER : FakeAmmo {};
	
	class Sh_105_ILLUM : FakeAmmo {};
	
	class Sh_105_SMOKE : FakeAmmo {};
	
	class 120mmHE_M120 : FakeAmmo {};
	
	class M_47_AT_EP1 : FakeAmmo {};
	
	class PMC_ied_v1 : FakeAmmo {};
	
	class PMC_ied_v2 : FakeAmmo {};
	
	class PMC_ied_v3 : FakeAmmo {};
	
	class PMC_ied_v4 : FakeAmmo {};
	
	class G_30mm_HE_heli : FakeAmmo {};
	
	class B_19mm_HE : FakeAmmo {};
};
