// Generated by unRap v1.06 by Kegetys

class CfgMovesBasic {
	class ManActions {
		GestureSwing = " ";
	};
	
	class Actions {
		class NoActions : ManActions {
			GestureSwing[] = {"GestureSwing", "Gesture"};
		};
	};
};
