// Generated by unRap v1.06 by Kegetys

class cfgWeapons {
	class Rifle;	// External class reference
	
	class MeleeWeapon : Rifle {
		distanceZoomMin = 50;
		distanceZoomMax = 50;
		canDrop = false;
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		optics = true;
		modelOptics = "-";
		modes[] = {"Single"};
		fireLightDuration = 0;
		fireLightIntensity = 0;
		reloadMagazineSound[] = {"", 1};
		
		class Single : DZ_SingleMelee {
			multiplier = 1;
			burst = 1;
			displayName = "Hack";
			dispersion = 0.2;
			optics = true;
			recoil = "DZ_Swing";
			autoFire = true;
			aiRateOfFire = 0.7;	// delay between shots at given distance
			aiRateOfFireDistance = 2.2;
			useAction = false;
			useActionTitle = "";
			recoilProne = "DZ_Swing";
			swing0[] = {"dayz_weapons\sounds\swing_0", 1.77828, 1, 30};
			swing1[] = {"dayz_weapons\sounds\swing_1", 1.77828, 1, 30};
			soundBegin[] = {"swing0", 0.5, "swing1", 0.5};
			drySound[] = {"", 1};
			reloadTime = 0;
			reloadMagazineSound[] = {"", 1};
			showToPlayer = true;
			minRange = 0;
			minRangeProbab = 0.8;
			midRange = 0.3;
			midRangeProbab = 0.8;
			maxRange = 3;
			maxRangeProbab = 0;
		};
		cursor = "Vehicle_Grenade_W";
		cursoraim = "Vehicle_Grenade_W";
		cursorSize = 1;
	};
	
	class MeleeHatchet : MeleeWeapon {
		scope = public;
		model = "\dayz_weapons\models\Hatchet_weaponized";
		picture = "\dayz_equip\textures\equip_hatchet_CA.paa";
		displayName = $STR_EQUIP_NAME_41;
		magazines[] = {"Hatchet_Swing"};
		handAnim[] = {"OFP2_ManSkeleton", "\dayz_weapons\anim\melee_hatchet_holding.rtm"};
		
		class ItemActions {
			class Use {
				text = $STR_ACTIONS_CHOPWOOD;
				script = "spawn player_chopWood;";
			};
			
			class Toolbelt {
				text = "Add to Toolbelt";
				script = "spawn player_addToolbelt;";
				use[] = {"MeleeHatchet"};
				output[] = {"ItemHatchet"};
			};
			
			class Drop {
				text = "Drop Hatchet";
				script = "spawn player_dropWeapon;";
				use[] = {"Hatchet_Swing"};
			};
		};
		
		class Library {
			libTextDesc = $STR_EQUIP_DESC_41;
		};
		descriptionShort = $STR_EQUIP_DESC_41;
	};
	
	class MeleeCrowbar : MeleeHatchet {
		scope = public;
		model = "\dayz_weapons\models\crowbar_weaponized";
		picture = "\dayz_weapons\textures\equip_crowbar_CA.paa";
		displayName = "Crowbar";
		magazines[] = {"Crowbar_Swing"};
		
		class ItemActions {
			class Toolbelt {
				text = "Add to Toolbelt";
				script = "spawn player_addToolbelt;";
				use[] = {"MeleeCrowbar"};
				output[] = {"ItemCrowbar"};
			};

			class Drop {
				text = "Drop Crowbar";
				script = "spawn player_dropWeapon;";
				use[] = {"Crowbar_Swing"};
			};
		};
		
		class Library {
			libTextDesc = $STR_EQUIP_DESC_47;
		};
		descriptionShort = $STR_EQUIP_DESC_47;
	};
	
	class Winchester1866 : Rifle {
		scope = public;
		model = "\dayz_weapons\models\Winchester1866";
		picture = "\dayz_weapons\textures\equip_winchester1866_CA.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		magazines[] = {"15Rnd_W1866_Slug", "15Rnd_W1866_Pellet"};
		optics = true;
		modelOptics = "-";
		displayname = $STR_WPN_NAME_1;
		modes[] = {"Single"};
		distanceZoomMin = 50;
		distanceZoomMax = 50;
		selectionFireAnim = "zasleh";
		handAnim[] = {"OFP2_ManSkeleton", "\Ca\weapons_E\Data\Anim\LeeEnfield.rtm"};
		
		class Single : Mode_SemiAuto {
			dispersion = 0.003;
			soundContinuous = 0;
			reloadTime = 1;
			reloadMagazineSound[] = {"\ca\sounds\weapons\rifles\M1014-reload", 0.316228, 1, 20};
			begin1[] = {"dayz_weapons\sounds\shotgun_0", 1.77828, 1, 1000};
			begin2[] = {"dayz_weapons\sounds\shotgun_1", 1.77828, 1, 1000};
			soundBegin[] = {"begin1", 0.5, "begin2", 0.5};
			drySound[] = {"ca\sounds\weapons\rifles\dry", 0.01, 1, 10};
			minRange = 0;
			minRangeProbab = 0.5;
			midRange = 60;
			midRangeProbab = 0.2;
			maxRange = 100;
			maxRangeProbab = 0.03;
			recoil = "recoil_single_primary_9outof10";
			recoilProne = "recoil_single_primary_prone_8outof10";
		};
		
		class Library {
			libTextDesc = $STR_WPN_DESC_1;
		};
		descriptionShort = $STR_WPN_DESC_1;
	};
	
	class MR43 : Winchester1866 {
		model = "\dayz_weapons\models\mr43";
		picture = "\dayz_weapons\textures\equip_mr43_CA.paa";
		displayname = $STR_WPN_NAME_5;
		descriptionShort = $STR_WPN_DESC_5;
		magazines[] = {"2Rnd_shotgun_74Slug", "2Rnd_shotgun_74Pellets"};
		
		class Single : Mode_SemiAuto {
			dispersion = 0.003;
			soundContinuous = 0;
			reloadTime = 2;
			reloadMagazineSound[] = {"\ca\sounds\weapons\rifles\M1014-reload", 0.316228, 1, 20};
			DB_shotgun_1[] = {"dayz_weapons\sounds\DB_shotgun_1", 1.77828, 1, 1000};
			soundBegin[] = {"DB_shotgun_1", 1};
			drySound[] = {"ca\sounds\weapons\rifles\dry", 0.01, 1, 10};
			minRange = 0;
			minRangeProbab = 0.5;
			midRange = 60;
			midRangeProbab = 0.2;
			maxRange = 100;
			maxRangeProbab = 0.03;
			recoil = "recoil_single_primary_9outof10";
			recoilProne = "recoil_single_primary_prone_8outof10";
		};
	};
	
	class Remington870 : Winchester1866 {
		model = "\dayz_weapons\models\Remington870";
		picture = "\dayz_weapons\textures\equip_remington870_CA.paa";
		displayname = $STR_WPN_NAME_2;
		descriptionShort = $STR_WPN_DESC_2;
		magazines[] = {"8Rnd_B_Beneli_74Slug", "8Rnd_B_Beneli_Pellets"};
	};
	
	class Remington870_lamp : Remington870 {
		model = "\dayz_weapons\models\Remington870_lamp";
		displayname = $STR_WPN_NAME_3;
		descriptionShort = $STR_WPN_DESC_3;
		magazines[] = {"8Rnd_B_Beneli_74Slug", "8Rnd_B_Beneli_Pellets"};
		
		class FlashLight {
			color[] = {0.9, 0.9, 0.7, 0.9};
			ambient[] = {0.1, 0.1, 0.1, 1};
			position = "flash dir";
			direction = "flash";
			angle = 30;
			scale[] = {1, 1, 0.5};
			brightness = 0.1;
		};
	};
	class GrenadeLauncher;	// External class reference
	
	class Flare : GrenadeLauncher {
		scope = public;
		autoAimEnabled = false;
		cursor = "Vehicle_Grenade_W";
		cursoraim = "\ca\Weapons\Data\clear_empty";
		cursorSize = 1;
		value = 0;
		type = VSoft;
		displayName = $STR_MAG_ACTION2_4;
		canDrop = false;
		muzzles[] = {"RoadFlareMuzzle", "ChemLightMuzzle", "MolotovCocktailMuzzle"};
		
		class ThrowMuzzle : GrenadeLauncher {
			cursor = "Air_Dot";
			cursoraim = "Vehicle_Grenade_W";
			cursorSize = 1;
			sound[] = {"", 0.000316228, 1};
			reloadSound[] = {"", 0.000316228, 1};
			aiDispersionCoefX = 6;
			aiDispersionCoefY = 6;
			reloadTime = 0;
			magazineReloadTime = 0;
			enableAttack = false;
			showEmpty = 0;
			autoReload = true;
			modelOptics = "";
			minRange = 30;
			minRangeProbab = 0.5;
			midRange = 45;
			midRangeProbab = 0.2;
			maxRange = 60;
			maxRangeProbab = 0.03;
		};
		
		class RoadFlareMuzzle : ThrowMuzzle {
			displayName = $STR_MAG_ACTION_4;
			magazines[] = {"HandRoadFlare"};
			cursor = "Vehicle_Grenade_W";
			cursorAim = "\ca\Weapons\Data\clear_empty";
			begin1[] = {"dayz_weapons\sounds\roadflare_start", 1.77828, 1, 1000};
			soundBegin[] = {"begin1", 1};
		};
		
		class ChemLightMuzzle : ThrowMuzzle {
			displayName = $STR_MAG_ACTION_5;
			magazines[] = {"HandChemGreen", "HandChemRed", "HandChemBlue"};
			cursor = "Vehicle_Grenade_W";
			cursorAim = "\ca\Weapons\Data\clear_empty";
		};
		
		class MolotovCocktailMuzzle : ThrowMuzzle {
			displayName = "Throw";
			magazines[] = {"TrashJackDaniels", "ItemSodaEmpty", "TrashTinCan"};
			cursor = "Vehicle_Grenade_W";
			cursorAim = "\ca\Weapons\Data\clear_empty";
		};
	};
	
	class Crossbow : Winchester1866 {
		scope = public;
		value = 1;
		model = "\dayz_weapons\models\testgun";
		optics = true;
		dexterity = 1.64;
		displayName = $STR_WPN_NAME_4;
		picture = "\dayz_weapons\textures\equip_crossbow_ca.paa";
		UiPicture = "\CA\weapons\data\Ico\i_regular_CA.paa";
		drySound[] = {"Ca\sounds\Weapons\rifles\dry", 0.000316228, 1, 10};
		fireLightDuration = 0;
		fireLightIntensity = 0;
		reloadMagazineSound[] = {"ca\sounds\weapons\rifles\reload-m16-3", 0.0562341, 1, 20};
		
		class Library {
			libTextDesc = $STR_WPN_DESC_4;
		};
		descriptionShort = $STR_WPN_DESC_4;
		
		class Single : Mode_SemiAuto {
			dispersion = 0.001;
			soundContinuous = 0;
			reloadTime = 2.5;
			reloadMagazineSound[] = {"\ca\sounds\weapons\rifles\M1014-reload", 0.316228, 1, 20};
			begin1[] = {"dayz_weapons\sounds\crossbow_fire_0", 0.177828, 1, 15};
			begin2[] = {"dayz_weapons\sounds\crossbow_fire_1", 0.177828, 1, 15};
			soundBegin[] = {"begin1", 0.5, "begin2", 0.5};
			drySound[] = {"ca\sounds\weapons\rifles\dry", 0.01, 1, 10};
			minRange = 0;
			minRangeProbab = 0.5;
			midRange = 60;
			midRangeProbab = 0.2;
			maxRange = 100;
			maxRangeProbab = 0.03;
			recoil = "recoil_single_primary_4outof10";
			recoilProne = "recoil_single_primary_prone_4outof10";
		};
		magazines[] = {"BoltSteel"};
		bullet1[] = {"dayz_weapons\sounds\crossbow_bolt", 0.177828, 1, 15};
		soundBullet[] = {"bullet1", 1};
	};
	class M249;	// External class reference
	
	class M249_DZ : M249 {
		type = "1";
	};

	/*
	class M240;	// External class reference
	
	class M240_DZ : M240 {
		type = "1";
	};
	*/

	class Mk_48;	// External class reference
	
	class Mk_48_DZ : Mk_48 {
		type = "1";
	};

	/*
	class M107;	// External class reference
	
	class M107_DZ : M107 {
		type = "1";
	};
	class m107_TWS_EP1;	// External class reference
	
	class m107_TWS_EP1_DZ : m107_TWS_EP1 {
		type = "1";
	};
	*/

	class LeeEnfield_RX : Rifle {
		htMin = 1;
		htMax = 420;
		afMax = 0;
		mfMax = 0;
		mFact = 1;
		tBody = 100;
		scope = public;
		displayName = "$STR_EP1_DN_LeeEnfield";
		model = "\CA\weapons_E\LeeEnfield\LeeEnfield_no4mk1";
		picture = "\ca\weapons_E\Data\icons\leeEnfield_CA.paa";
		UiPicture = "\CA\weapons\data\Ico\i_sniper_CA.paa";
		handAnim[] = {"OFP2_ManSkeleton", "\Ca\weapons_E\Data\Anim\LeeEnfield.rtm"};
		dexterity = 1.61;
		magazines[] = {"10x_303_RX"};
		opticsDisablePeripherialVision = false;
		opticsPPEffects[] = {};
		distanceZoomMin = 300;
		distanceZoomMax = 300;
		minRange = 0;
		minRangeProbab = 0.1;
		midRange = 150;
		midRangeProbab = 0.7;
		maxRange = 300;
		maxRangeProbab = 0.05;
		aiRateOfFire = 8.0;	// delay between shots at given distance
		aiRateOfFireDistance = 600;
		dispersion = 0.0005;
		
		class Library {
			libTextDesc = "$STR_EP1_LIB_LeeEnfield";
		};
		descriptionShort = "$STR_EP1_DSS_LeeEnfield";
		begin1[] = {"Ca\Sounds_E\Weapons_E\Enfield\Enfield_4", 1.77828, 1, 1500};
		soundBegin[] = {"begin1", 1};
		reloadMagazineSound[] = {"Ca\sounds\Weapons\rifles\M1014-reload", 0.01, 1, 20};
		drySound[] = {"Ca\sounds\Weapons\rifles\dry", 0.01, 1, 10};
		reloadTime = 2;
		backgroundReload = true;
		recoil = "recoil_single_primary_6outof10";
		recoilProne = "recoil_single_primary_prone_5outof10";
		value = 1000;
	};
};
