// Generated by unRap v1.06 by Kegetys

class DZ_SingleMelee : Mode_SemiAuto {
	multiplier = 1;
	burst = 5;
	displayName = "Hack";
	dispersion = 0.2;
	sound[] = {"", 0, 1};
	soundContinuous = 1;
	reloadTime = 1;
	magazineReloadTime = 1;
	ffCount = 1;
	optics = "false";
	recoil = "empty";
	autoFire = "true";
	aiRateOfFire = 0.7;	// delay between shots at given distance
	aiRateOfFireDistance = 2.2;
	useAction = "false";
	useActionTitle = "";
	recoilProne = "empty";
	showToPlayer = "true";
	minRange = 0;
	minRangeProbab = 0.8;
	midRange = 0.3;
	midRangeProbab = 0.8;
	maxRange = 3;
	maxRangeProbab = 0;
	soundBurst = 1;
};
