// Generated by unRap v1.06 by Kegetys

class FlareSparks {
	class FlareSmoke {
		simulation = "particles";
		type = "FlareSmoke";
		position[] = {0, 0, 0};
		intensity = 1;
		interval = 1;
		lifeTime = 1;
	};
	
	class FlareSparks {
		simulation = "particles";
		type = "FlareSparks";
		position[] = {0, 0, 0};
		intensity = 1;
		interval = 1;
		lifeTime = 1;
	};
};
