// Generated by unRap v1.06 by Kegetys

class GlassSmash {
	class BottleGlassShards {
		simulation = "particles";
		type = "BottleGlassShards";
		position[] = {0, 0, 0};
		intensity = 1;
		interval = 1;
		lifeTime = 1;
	};
	
	class BottleGlassShards2 {
		simulation = "particles";
		type = "BottleGlassShards2";
		position[] = {0, 0, 0};
		intensity = 1;
		interval = 1;
		lifeTime = 1;
	};
	
	class BottleGlassDust {
		simulation = "particles";
		type = "BottleGlassDust";
		position[] = {0, 0, 0};
		intensity = 1;
		interval = 1;
		lifeTime = 1;
	};
};
