// Generated by unRap v1.06 by Kegetys

class Mode_SemiAuto {
	multiplier = 1;
	burst = 1;
	dispersion = 0.0002;
	sound[] = {"", 10, 1};
	soundBegin[] = {"sound", 1};
	soundEnd[] = {};
	soundLoop[] = {};
	soundContinuous = 0;
	soundBurst = 1;
	reloadTime = 0.1;
	ffCount = 1;
	ffMagnitude = 0.5;
	ffFrequency = 11;
	flash = "gunfire";
	flashSize = 0.1;
	recoil = "Empty";
	recoilProne = "Empty";
	autoFire = false;
	aiRateOfFire = 0.5;	// delay between shots at given distance
	aiRateOfFireDistance = 500;
	useAction = false;
	useActionTitle = "";
	showToPlayer = true;
	minRange = 30;
	minRangeProbab = 0.25;
	midRange = 300;
	midRangeProbab = 0.58;
	maxRange = 600;
	maxRangeProbab = 0.04;
	displayName = "Semi";
};
