// Generated by unRap v1.06 by Kegetys

class CfgFaces {
	class Default;	// External class reference
	
	class Man : Default {
		class Default;	// External class reference
		
		class Zombie1 : Default {
			name = "Zombie 1";
			texture = "\dayz\textures\faces\zombie_01_co.paa";
			identityTypes[] = {"Zombie1"};
			disabled = 0;
		};
		
		class Zombie2 : Default {
			name = "Zombie 2";
			texture = "\dayz\textures\faces\zombie_02_co.paa";
			identityTypes[] = {"Zombie2"};
			disabled = 0;
		};

		class Zombie3 : Default {
			name = "Zombie 3";
			texture = "\dayz\textures\faces\zombie_03_co.paa";
			identityTypes[] = {"Zombie3"};
			disabled = 0;
		};
	};
};
