// config.bin - 18:25:01 03/25/13, generated in 6.16 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Enabled, Automatic comments: Enabled

#define ReadAndWrite		0
#define ReadAndCreate		1
#define ReadOnly		2
#define ReadOnlyVerified		3

#define private		0
#define protected		1
#define public		2

#define true	1
#define false	0

#include "CfgPatches.hpp"
#include "CfgVehicleClasses.hpp"
class RscPicture;	// External class reference
#include "RscTitles.hpp"
class RscStandardDisplay;	// External class reference
#include "DayZMontage.hpp"
#include "CfgMovesBasic.hpp"
#include "CfgMovesMaleSdr.hpp"
#include "CfgMovesZombie.hpp"
#include "CfgTownGenerator.hpp"
#include "CfgTownGeneratorUtes.hpp"
#include "CfgFaces.hpp"
#include "CfgVoice.hpp"
#include "CfgIdentities.hpp"
#include "cfgBody.hpp"
#include "CfgVehicles.hpp"
