// Generated by unRap v1.06 by Kegetys

class RscTitles {
	titles[] = {"DeathScreenBG","DeathScreen1", "DeathScreen2", "DeathScreen3", "DeathScreen4", "DeathScreen5", "DeathScreen6", "DeathScreen7", "TitleScreen", "RscTitleStructuredText"};
	
	class DeathScreenBG {
		idd = -1;
		movingEnable = "false";
		duration = 120;
		fadein = 0;
		name = "DeathScreenBG";
		controls[] = {"DeathScreenBG"};
		
		class DeathScreenBG : RscPicture {
			x = "0.00001 * safezoneW + safezoneX";
			y = "0.00001 * safezoneH + safezoneY";
			w = "1 * safezoneW";
			h = "1 * safezoneH";
			colorBackground[] = { 0, 0, 0, 1 };
			text = "";
		};
	};

	class DeathScreen1 {
		idd = -1;
		movingEnable = "false";
		duration = 120;
		fadein = 0;
		name = "DeathScreen1";
		controls[] = {"DeathScreen1"};
		
		class DeathScreen1 : RscPicture {
			x = "0.00001 * safezoneW + safezoneX";
			y = "0.00001 * safezoneH + safezoneY";
			w = "1 * safezoneW";
			h = "1 * safezoneH";
			text = "\dayz\ui\screen_death_ca_1.paa";
			colorBackground[] = { 0, 0, 0, 0 };
		};
	};

	class DeathScreen2 {
		idd = -1;
		movingEnable = "false";
		duration = 120;
		fadein = 0;
		name = "DeathScreen2";
		controls[] = {"DeathScreen2"};
		
		class DeathScreen2 : RscPicture {
			x = "0.00001 * safezoneW + safezoneX";
			y = "0.00001 * safezoneH + safezoneY";
			w = "1 * safezoneW";
			h = "1 * safezoneH";
			text = "\dayz\ui\screen_death_ca_2.paa";
			colorBackground[] = { 0, 0, 0, 0 };
		};
	};

	class DeathScreen3 {
		idd = -1;
		movingEnable = "false";
		duration = 120;
		fadein = 0;
		name = "DeathScreen3";
		controls[] = {"DeathScreen3"};
		
		class DeathScreen3 : RscPicture {
			x = "0.00001 * safezoneW + safezoneX";
			y = "0.00001 * safezoneH + safezoneY";
			w = "1 * safezoneW";
			h = "1 * safezoneH";
			text = "\dayz\ui\screen_death_ca_3.paa";
			colorBackground[] = { 0, 0, 0, 0 };
		};
	};

	class DeathScreen4 {
		idd = -1;
		movingEnable = "false";
		duration = 120;
		fadein = 0;
		name = "DeathScreen4";
		controls[] = {"DeathScreen4"};
		
		class DeathScreen4 : RscPicture {
			x = "0.00001 * safezoneW + safezoneX";
			y = "0.00001 * safezoneH + safezoneY";
			w = "1 * safezoneW";
			h = "1 * safezoneH";
			text = "\dayz\ui\screen_death_ca_4.paa";
			colorBackground[] = { 0, 0, 0, 0 };
		};
	};

	class DeathScreen5 {
		idd = -1;
		movingEnable = "false";
		duration = 120;
		fadein = 0;
		name = "DeathScreen5";
		controls[] = {"DeathScreen5"};
		
		class DeathScreen5 : RscPicture {
			x = "0.00001 * safezoneW + safezoneX";
			y = "0.00001 * safezoneH + safezoneY";
			w = "1 * safezoneW";
			h = "1 * safezoneH";
			text = "\dayz\ui\screen_death_ca_5.paa";
			colorBackground[] = { 0, 0, 0, 0 };
		};
	};

	class DeathScreen6 {
		idd = -1;
		movingEnable = "false";
		duration = 120;
		fadein = 0;
		name = "DeathScreen6";
		controls[] = {"DeathScreen6"};
		
		class DeathScreen6 : RscPicture {
			x = "0.00001 * safezoneW + safezoneX";
			y = "0.00001 * safezoneH + safezoneY";
			w = "1 * safezoneW";
			h = "1 * safezoneH";
			text = "\dayz\ui\screen_death_ca_6.paa";
			colorBackground[] = { 0, 0, 0, 0 };
		};
	};

	class DeathScreen7 {
		idd = -1;
		movingEnable = "false";
		duration = 120;
		fadein = 0;
		name = "DeathScreen7";
		controls[] = {"DeathScreen7"};
		
		class DeathScreen7 : RscPicture {
			x = "0.00001 * safezoneW + safezoneX";
			y = "0.00001 * safezoneH + safezoneY";
			w = "1 * safezoneW";
			h = "1 * safezoneH";
			text = "\dayz\ui\screen_death_ca_7.paa";
			colorBackground[] = { 0, 0, 0, 0 };
		};
	};
	
	class TitleScreen {
		idd = -1;
		movingEnable = "false";
		duration = 120;
		fadein = 0;
		name = "TitleScreen";
		controls[] = {"TitleScreen"};
		
		class TitleScreen : RscPicture {
			x = "0.00001 * safezoneW + safezoneX";
			y = "0.00001 * safezoneH + safezoneY";
			w = "1 * safezoneW";
			h = "1 * safezoneH";
			text = "\dayz\ui\screen_title_ca.paa";
			colorBackground[] = { 0, 0, 0, 0 };
		};
	};
};
