// Generated by unRap v1.06 by Kegetys

class CfgSFX {
	class Generator1 {
		sounds[] = {"Generator1"};
		name = "Generator1";
		Generator1[] = {"\dayz_sfx\effects\generator1", 3.16228, 1, 200, 1, 0, 0, 0};
		Empty[] = {"", 0, 0, 0, 0, 0, 0, 0};
	};
};
