// Generated by unRap v1.06 by Kegetys

class CfgVehicles {
	class Sound;	// External class reference
	
	class Sound_Generator1 : Sound {
		scope = public;
		sound = "Generator1";
		displayName = "Generator";
	};
};
