// config.bin - 20:57:41 12/11/12, generated in 0.05 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Enabled, Automatic comments: Enabled

#define private		0
#define protected		1
#define public		2

#include "CfgPatches.hpp"
#include "CfgVehicles.hpp"
#include "CfgSFX.hpp"
#include "CfgSounds.hpp"
#include "CfgMusic.hpp"
